# Generated by Django 6.1 on 2026-08-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
