# Generated by Django 6.1 on 2026-08-22 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_status'),
        ('staff', '0003_alter_staffprofile_is_active'),
        ('tenants', '0005_tenant_max_properties_tenant_max_rooms_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'ordering': ['name']},
        ),
        migrations.RemoveIndex(
            model_name='staffprofile',
            name='staff_profi_departm_fd308c_idx',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='hired_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='staffprofile',
            index=models.Index(fields=['position'], name='staff_profi_positio_469bdd_idx'),
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='phone',
        ),
    ]
