# Generated by Django 6.1 on 2026-08-22 18:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_status'),
        ('staff', '0004_alter_staffprofile_options_and_more'),
        ('tenants', '0005_tenant_max_properties_tenant_max_rooms_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='staffprofile',
            index=models.Index(fields=['tenant', 'is_active'], name='staff_profi_tenant__15eb36_idx'),
        ),
    ]
