# Generated by Django 6.1 on 2026-08-26 08:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0005_tenant_max_properties_tenant_max_rooms_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('account_type', models.CharField(choices=[('CASH', 'Cash / Drawer'), ('BANK', 'Bank Account'), ('WALLET', 'POS Machine / Digital Wallet')], default='CASH', max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('iban', models.CharField(blank=True, max_length=50)),
                ('branch_name', models.CharField(blank=True, max_length=100)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_accounts', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-is_default', 'name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AccountTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transfer_date', models.DateField(default=django.utils.timezone.now)),
                ('reference_number', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_transfers', to='tenants.tenant')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_sent', to='accounts.paymentaccount')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_received', to='accounts.paymentaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('INFLOW', 'Inflow / Credit'), ('OUTFLOW', 'Outflow / Debit'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('source_module', models.CharField(choices=[('BOOKING', 'Booking Payment'), ('POS', 'Restaurant POS'), ('EXPENSE', 'Expense Payment'), ('TRANSFER', 'Internal Transfer'), ('MANUAL', 'Manual Adjustment')], max_length=30)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_transactions', to='tenants.tenant')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.paymentaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
