# Generated by Django 6.1 on 2026-09-24 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_paymenttransaction'),
        ('properties', '0003_remove_property_properties_city_c34f4f_idx_and_more'),
        ('tenants', '0005_tenant_max_properties_tenant_max_rooms_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentaccount',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_accounts', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='account_type',
            field=models.CharField(choices=[('CASH', 'Cash Drawer'), ('BANK', 'Bank Account'), ('ONLINE', 'Online Gateway'), ('OTHER', 'Other')], default='CASH', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='paymentaccount',
            unique_together={('tenant', 'property', 'name')},
        ),
    ]
