# Generated by Django 6.1 on 2026-09-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_paymentaccount_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttransfer',
            name='receipt_image',
            field=models.FileField(blank=True, null=True, upload_to='transfer_receipts/'),
        ),
    ]
