[project]
name = "hotel-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Siraj Tariq Lenovo", email = "sirajtariq0@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "django>=6.1",
    "django-cors-headers>=4.9.0",
    "django-environ>=0.14.0",
    "djangorestframework>=3.18.0",
    "djangorestframework-camel-case>=1.4.2",
    "djangorestframework-simplejwt>=5.5.1",
    "drf-spectacular>=0.30.0",
    "gunicorn>=26.2.0",
    "psycopg[binary]>=3.3.4",
    "whitenoise>=6.12.0",
]

[project.scripts]
hotel-server = "hotel_server:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
