# Generated by Django 6.1 on 2026-08-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diningtable',
            name='floor_or_section',
            field=models.CharField(blank=True, default='Ground Floor', max_length=100),
        ),
    ]
