from django.db.models import Sum, Count
from rest_framework import viewsets, status
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from rest_framework_simplejwt.tokens import RefreshToken
from apps.tenants.models import Tenant
from apps.tenants.serializers import TenantListSerializer, TenantDetailSerializer, TenantSerializer
from apps.tenants.services.tenant_service import TenantService
from apps.users.models import User
from apps.users.serializers import UserSerializer
from core.permissions import IsSuperAdmin

class TenantViewSet(viewsets.ModelViewSet):
    permission_classes = [IsSuperAdmin]

    def get_serializer_class(self):
        if self.action == 'list':
            return TenantListSerializer
        return TenantDetailSerializer

    def get_queryset(self):
        user = self.request.user
        if not user or not user.is_authenticated:
            return Tenant.objects.none()
        if user.is_superuser or getattr(user, 'role', '') == 'SUPERADMIN':
            tenants = Tenant.objects.annotate(
                current_properties_count=Count('properties', distinct=True),
                current_rooms_count=Count('properties__rooms', distinct=True),
                current_users_count=Count('users', distinct=True)
            ).order_by('-created_at')
            for tenant in tenants:
                TenantService.calculate_subscription_status(tenant)
            return tenants

        return Tenant.objects.none()

    @action(detail=False, methods=['get'], permission_classes=[IsAuthenticated])
    def me(self, request):
        """
        Returns current tenant details for the authenticated user.
        Accessible by any authenticated user (SuperAdmin, TenantAdmin, PropertyManager, Staff).
        """
        user = request.user
        if not user or not user.is_authenticated:
            return Response({'detail': 'Authentication required.'}, status=status.HTTP_401_UNAUTHORIZED)
        
        tenant = getattr(user, 'tenant', None)
        if not tenant:
            return Response({'detail': 'User is not associated with any active tenant.'}, status=status.HTTP_404_NOT_FOUND)

        TenantService.calculate_subscription_status(tenant)
        serializer = self.get_serializer(tenant)
        return Response(serializer.data, status=status.HTTP_200_OK)

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        tenant = TenantService.create_tenant(**serializer.validated_data)
        response_serializer = self.get_serializer(tenant)
        return Response(response_serializer.data, status=status.HTTP_201_CREATED)

    def update(self, request, *args, **kwargs):
        partial = kwargs.pop('partial', False)
        instance = self.get_object()
        serializer = self.get_serializer(instance, data=request.data, partial=partial)
        serializer.is_valid(raise_exception=True)
        updated_tenant = TenantService.update_tenant(instance, **serializer.validated_data)
        response_serializer = self.get_serializer(updated_tenant)
        return Response(response_serializer.data)

    @action(detail=True, methods=['post'], permission_classes=[IsSuperAdmin])
    def impersonate(self, request, pk=None):
        """
        Generates impersonation tokens for SuperAdmin to log in as a Tenant Admin.
        """
        tenant = self.get_object()
        
        # Find active TENANT_ADMIN user for this tenant
        tenant_admin = User.objects.filter(tenant=tenant, role='TENANT_ADMIN', is_active=True).first()
        if not tenant_admin:
            # Fallback to any user of this tenant
            tenant_admin = User.objects.filter(tenant=tenant, is_active=True).first()

        if not tenant_admin:
            # Auto-create fallback admin if no user exists for this tenant
            admin_username = f"admin_{tenant.slug}"
            admin_email = tenant.contact_email or f"admin@{tenant.slug}.com"
            tenant_admin = User.objects.create_user(
                username=admin_username,
                email=admin_email,
                password='AutoGeneratedImpersonationPass123!',
                role='TENANT_ADMIN',
                tenant=tenant
            )

        refresh = RefreshToken.for_user(tenant_admin)
        refresh['is_impersonated'] = True
        refresh['original_superadmin_id'] = request.user.id
        refresh['role'] = tenant_admin.role
        refresh['tenant_id'] = tenant.id

        return Response({
            'access': str(refresh.access_token),
            'refresh': str(refresh),
            'user': UserSerializer(tenant_admin).data,
            'is_impersonated': True,
            'original_superadmin_id': request.user.id,
            'tenant_name': tenant.name
        }, status=status.HTTP_200_OK)

    @action(detail=True, methods=['post'], permission_classes=[IsSuperAdmin])
    def record_subscription_payment(self, request, pk=None):
        """
        Records a subscription payment for a tenant and extends the next_due_date.
        """
        tenant = self.get_object()
        amount_paid = float(request.data.get('amount_paid', tenant.price_amount or 0.00))
        payment_method = request.data.get('payment_method', 'BANK_TRANSFER')
        months_to_extend = int(request.data.get('months_to_extend', 1))

        updated_tenant = TenantService.record_payment(
            tenant=tenant,
            amount_paid=amount_paid,
            payment_method=payment_method,
            months_to_extend=months_to_extend
        )

        return Response(self.get_serializer(updated_tenant).data, status=status.HTTP_200_OK)

    @action(detail=False, methods=['get'], permission_classes=[IsSuperAdmin])
    def metrics(self, request):
        """
        Returns platform-wide financial & tenant metrics for SuperAdmin.
        """
        tenants = Tenant.objects.all()
        for tenant in tenants:
            TenantService.calculate_subscription_status(tenant)

        total_tenants = tenants.count()
        active_tenants = tenants.filter(is_active=True).count()
        inactive_tenants = total_tenants - active_tenants

        monthly_mrr = tenants.filter(is_active=True, billing_type='MONTHLY').aggregate(
            total=Sum('price_amount')
        )['total'] or 0.00

        one_time_sales = tenants.filter(billing_type='ONE_TIME').aggregate(
            total=Sum('price_amount')
        )['total'] or 0.00

        annual_arr = tenants.filter(is_active=True, billing_type='ANNUAL').aggregate(
            total=Sum('price_amount')
        )['total'] or 0.00

        overdue_count = tenants.filter(subscription_status='OVERDUE').count()
        due_soon_count = tenants.filter(subscription_status='DUE_SOON').count()

        return Response({
            'totalTenants': total_tenants,
            'activeTenants': active_tenants,
            'inactiveTenants': inactive_tenants,
            'monthlyRecurringRevenue': float(monthly_mrr),
            'oneTimeRevenue': float(one_time_sales),
            'annualRecurringRevenue': float(annual_arr),
            'overdueCount': overdue_count,
            'dueSoonCount': due_soon_count,
            # Legacy snake_case fallbacks
            'total_tenants': total_tenants,
            'active_tenants': active_tenants,
            'inactive_tenants': inactive_tenants,
            'monthly_recurring_revenue': float(monthly_mrr),
            'one_time_revenue': float(one_time_sales),
            'annual_recurring_revenue': float(annual_arr),
            'overdue_count': overdue_count,
            'due_soon_count': due_soon_count,
        })

    @action(detail=False, methods=['get'], permission_classes=[IsSuperAdmin], url_path='platform-analytics')
    def platform_analytics(self, request):
        """
        Returns aggregated MRR, ARR, active tenant counts and ultra-lean subscription breakdown list.
        """
        tenants = Tenant.objects.all()
        for tenant in tenants:
            TenantService.calculate_subscription_status(tenant)

        total_registered = tenants.count()
        active_tenants = tenants.filter(is_active=True)
        active_count = active_tenants.count()

        mrr = 0.0
        for t in active_tenants:
            amount = float(t.price_amount or 0)
            if t.billing_type == 'ANNUAL':
                mrr += (amount / 12)
            else:
                mrr += amount

        arr = mrr * 12

        breakdown = []
        for t in tenants.order_by('-price_amount', '-created_at'):
            breakdown.append({
                'id': t.id,
                'name': t.name,
                'slug': t.slug,
                'subscriptionPlan': t.subscription_plan,
                'billingType': t.billing_type,
                'priceAmount': float(t.price_amount or 0),
                'subscriptionStatus': t.subscription_status,
                'nextDueDate': t.next_due_date,
                'isActive': t.is_active,
                # snake_case aliases
                'subscription_plan': t.subscription_plan,
                'billing_type': t.billing_type,
                'price_amount': float(t.price_amount or 0),
                'subscription_status': t.subscription_status,
                'next_due_date': t.next_due_date,
                'is_active': t.is_active,
            })

        return Response({
            'metrics': {
                'monthlyMrr': round(mrr, 2),
                'estimatedArr': round(arr, 2),
                'oneTimeRevenue': 0.0,
                'activeTenantsCount': active_count,
                'totalTenantsCount': total_registered,
                # snake_case aliases
                'monthly_mrr': round(mrr, 2),
                'estimated_arr': round(arr, 2),
                'one_time_revenue': 0.0,
                'active_tenants_count': active_count,
                'total_tenants_count': total_registered,
            },
            'breakdown': breakdown
        })

    @action(detail=True, methods=['get'], permission_classes=[IsSuperAdmin], url_path='subscription-history')
    def subscription_history(self, request, pk=None):
        """
        Returns invoice & billing payment history for a specific tenant.
        """
        tenant = self.get_object()
        TenantService.calculate_subscription_status(tenant)

        history = [
            {
                'id': f"INV-SAAS-{tenant.id}-01",
                'invoiceDate': tenant.subscription_start_date,
                'dueDate': tenant.next_due_date,
                'plan': tenant.subscription_plan,
                'billingType': tenant.billing_type,
                'amountPaid': float(tenant.price_amount or 0),
                'paymentMethod': 'Bank Transfer / Manual Admin',
                'status': tenant.subscription_status,
                # snake_case aliases
                'invoice_date': tenant.subscription_start_date,
                'due_date': tenant.next_due_date,
                'billing_type': tenant.billing_type,
                'amount_paid': float(tenant.price_amount or 0),
                'payment_method': 'Bank Transfer / Manual Admin',
            }
        ]
        return Response({
            'tenantId': tenant.id,
            'tenantName': tenant.name,
            'currentPlan': tenant.subscription_plan,
            'nextDueDate': tenant.next_due_date,
            'history': history,
            # snake_case aliases
            'tenant_id': tenant.id,
            'tenant_name': tenant.name,
            'current_plan': tenant.subscription_plan,
            'next_due_date': tenant.next_due_date,
        })


