from django.db.models import Sum, Count
from rest_framework import viewsets, status
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from rest_framework_simplejwt.tokens import RefreshToken
from apps.tenants.models import Tenant
from apps.tenants.serializers import TenantSerializer
from apps.tenants.services.tenant_service import TenantService
from apps.users.models import User
from apps.users.serializers import UserSerializer
from core.permissions import IsSuperAdmin

class TenantViewSet(viewsets.ModelViewSet):
    serializer_class = TenantSerializer
    permission_classes = [IsSuperAdmin]

    def get_queryset(self):
        user = self.request.user
        if not user or not user.is_authenticated:
            return Tenant.objects.none()
        if user.is_superuser or getattr(user, 'role', '') == 'SUPERADMIN':
            # Eager-annotate counts to avoid N+1 query loops
            tenants = Tenant.objects.annotate(
                current_users_count=Count('users', distinct=True),
                current_properties_count=Count('properties', distinct=True),
                current_rooms_count=Count('properties__rooms', distinct=True)
            )
            for tenant in tenants:
                TenantService.calculate_subscription_status(tenant)
            return tenants

        return Tenant.objects.none()

    @action(detail=False, methods=['get'], permission_classes=[IsAuthenticated])
    def me(self, request):
        """
        Returns current tenant details for the authenticated user.
        Accessible by any authenticated user (SuperAdmin, TenantAdmin, PropertyManager, Staff).
        """
        user = request.user
        if not user or not user.is_authenticated:
            return Response({'detail': 'Authentication required.'}, status=status.HTTP_401_UNAUTHORIZED)
        
        tenant = getattr(user, 'tenant', None)
        if not tenant:
            return Response({'detail': 'User is not associated with any active tenant.'}, status=status.HTTP_404_NOT_FOUND)

        TenantService.calculate_subscription_status(tenant)
        serializer = self.get_serializer(tenant)
        return Response(serializer.data, status=status.HTTP_200_OK)



    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        tenant = TenantService.create_tenant(**serializer.validated_data)
        response_serializer = self.get_serializer(tenant)
        return Response(response_serializer.data, status=status.HTTP_201_CREATED)

    def update(self, request, *args, **kwargs):
        partial = kwargs.pop('partial', False)
        instance = self.get_object()
        serializer = self.get_serializer(instance, data=request.data, partial=partial)
        serializer.is_valid(raise_exception=True)
        updated_tenant = TenantService.update_tenant(instance, **serializer.validated_data)
        response_serializer = self.get_serializer(updated_tenant)
        return Response(response_serializer.data)

    @action(detail=True, methods=['post'], permission_classes=[IsSuperAdmin])
    def impersonate(self, request, pk=None):
        """
        Generates impersonation tokens for SuperAdmin to log in as a Tenant Admin.
        """
        tenant = self.get_object()
        
        # Find active TENANT_ADMIN user for this tenant
        tenant_admin = User.objects.filter(tenant=tenant, role='TENANT_ADMIN', is_active=True).first()
        if not tenant_admin:
            # Fallback to any user of this tenant
            tenant_admin = User.objects.filter(tenant=tenant, is_active=True).first()

        if not tenant_admin:
            # Auto-create fallback admin if no user exists for this tenant
            admin_username = f"admin_{tenant.slug}"
            admin_email = tenant.contact_email or f"admin@{tenant.slug}.com"
            tenant_admin = User.objects.create_user(
                username=admin_username,
                email=admin_email,
                password='AutoGeneratedImpersonationPass123!',
                role='TENANT_ADMIN',
                tenant=tenant
            )

        refresh = RefreshToken.for_user(tenant_admin)
        refresh['is_impersonated'] = True
        refresh['original_superadmin_id'] = request.user.id
        refresh['role'] = tenant_admin.role
        refresh['tenant_id'] = tenant.id

        return Response({
            'access': str(refresh.access_token),
            'refresh': str(refresh),
            'user': UserSerializer(tenant_admin).data,
            'is_impersonated': True,
            'original_superadmin_id': request.user.id,
            'tenant_name': tenant.name
        }, status=status.HTTP_200_OK)

    @action(detail=True, methods=['post'], permission_classes=[IsSuperAdmin])
    def record_subscription_payment(self, request, pk=None):
        """
        Records a subscription payment for a tenant and extends the next_due_date.
        """
        tenant = self.get_object()
        amount_paid = float(request.data.get('amount_paid', tenant.price_amount or 0.00))
        payment_method = request.data.get('payment_method', 'BANK_TRANSFER')
        months_to_extend = int(request.data.get('months_to_extend', 1))

        updated_tenant = TenantService.record_payment(
            tenant=tenant,
            amount_paid=amount_paid,
            payment_method=payment_method,
            months_to_extend=months_to_extend
        )

        return Response(self.get_serializer(updated_tenant).data, status=status.HTTP_200_OK)

    @action(detail=False, methods=['get'], permission_classes=[IsSuperAdmin])
    def metrics(self, request):
        """
        Returns platform-wide financial & tenant metrics for SuperAdmin.
        """
        tenants = Tenant.objects.all()
        for tenant in tenants:
            TenantService.calculate_subscription_status(tenant)

        total_tenants = tenants.count()
        active_tenants = tenants.filter(is_active=True).count()
        inactive_tenants = total_tenants - active_tenants

        monthly_mrr = tenants.filter(is_active=True, billing_type='MONTHLY').aggregate(
            total=Sum('price_amount')
        )['total'] or 0.00

        one_time_sales = tenants.filter(billing_type='ONE_TIME').aggregate(
            total=Sum('price_amount')
        )['total'] or 0.00

        annual_arr = tenants.filter(is_active=True, billing_type='ANNUAL').aggregate(
            total=Sum('price_amount')
        )['total'] or 0.00

        overdue_count = tenants.filter(subscription_status='OVERDUE').count()
        due_soon_count = tenants.filter(subscription_status='DUE_SOON').count()

        return Response({
            'total_tenants': total_tenants,
            'active_tenants': active_tenants,
            'inactive_tenants': inactive_tenants,
            'monthly_recurring_revenue': float(monthly_mrr),
            'one_time_revenue': float(one_time_sales),
            'annual_recurring_revenue': float(annual_arr),
            'overdue_count': overdue_count,
            'due_soon_count': due_soon_count,
        })


