# Generated by Django 6.1 on 2026-08-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'Maintenance'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=50),
        ),
    ]
