# Generated by Django 6.1 on 2026-08-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_status'),
        ('tenants', '0005_tenant_max_properties_tenant_max_rooms_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='property',
            name='properties_city_c34f4f_idx',
        ),
        migrations.RenameIndex(
            model_name='property',
            new_name='idx_prop_tenant_stat',
            old_name='properties_tenant__97a973_idx',
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['tenant', 'city'], name='idx_prop_tenant_city'),
        ),
    ]
