# Generated by Django 6.1 on 2026-08-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='billing_type',
            field=models.CharField(choices=[('MONTHLY', 'Monthly Subscription'), ('ONE_TIME', 'One-Time License'), ('ANNUAL', 'Annual Subscription')], default='MONTHLY', max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='price_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
