# Generated by Django 6.1 on 2026-08-22 06:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_billing_type_tenant_notes_tenant_price_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='grace_period_days',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='tenant',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('DUE_SOON', 'Due Soon'), ('GRACE_PERIOD', 'In Grace Period'), ('OVERDUE', 'Overdue')], default='PAID', max_length=30),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['subscription_status'], name='tenants_subscri_f58e68_idx'),
        ),
    ]
