# Generated by Django 6.1 on 2026-08-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_grace_period_days_tenant_next_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='subscription_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('DUE_SOON', 'Due Soon'), ('GRACE_PERIOD', 'In Grace Period'), ('OVERDUE', 'Overdue')], db_index=True, default='PAID', max_length=30),
        ),
    ]
