# Generated by Django 6.1 on 2026-08-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_alter_tenant_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='max_properties',
            field=models.PositiveIntegerField(blank=True, help_text='Max properties allowed. Null = Unlimited.', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='max_rooms',
            field=models.PositiveIntegerField(blank=True, help_text='Max rooms allowed. Null = Unlimited.', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='max_users',
            field=models.PositiveIntegerField(blank=True, help_text='Max login user accounts allowed. Null = Unlimited.', null=True),
        ),
    ]
