# Generated by Django 6.1 on 2026-08-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_status'),
        ('users', '0002_role_user_custom_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_properties',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='properties.property'),
        ),
    ]
