# Generated by Django 6.1 on 2026-08-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_check_in_date_and_more'),
        ('properties', '0002_alter_property_status'),
        ('rooms', '0002_alter_room_status'),
        ('tenants', '0005_tenant_max_properties_tenant_max_rooms_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['tenant', 'status', 'check_in_date'], name='bookings_tenant__5e4935_idx'),
        ),
    ]
