# Generated by Django 6.1 on 2026-08-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_booking_type_booking_check_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Tax percentage e.g. 15.00 for 15%', max_digits=5),
        ),
    ]
