# Generated by Django 6.1 on 2026-08-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_subtotal_amount_booking_tax_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_type',
            field=models.CharField(choices=[('FLAT', 'Flat Amount (PKR)'), ('PERCENTAGE', 'Percentage (%)')], default='FLAT', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
