# Generated by Django 6.1 on 2026-08-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_discount_amount_booking_discount_type_and_more'),
        ('properties', '0002_alter_property_status'),
        ('rooms', '0005_room_amenities_roomtype_amenities'),
        ('tenants', '0005_tenant_max_properties_tenant_max_rooms_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='booking',
            new_name='idx_bk_tenant_prop_stat',
            old_name='bookings_tenant__f290e6_idx',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_reference',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['tenant', 'check_in_date', 'check_out_date'], name='idx_bk_tenant_dates'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['tenant', 'booking_reference'], name='idx_bk_tenant_ref'),
        ),
    ]
