# Generated by Django 6.1 on 2026-09-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_rename_bookings_tenant__f290e6_idx_idx_bk_tenant_prop_stat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_refunded',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
