# Generated by Django 6.1 on 2026-09-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_booking_commission_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='extra_charges',
            field=models.JSONField(blank=True, default=list, help_text="List of extra charges dictionaries, e.g., [{'name': 'Laundry', 'amount': 500}]"),
        ),
    ]
