# Generated by Django 6.1 on 2026-09-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_booking_extra_charges'),
        ('properties', '0003_remove_property_properties_city_c34f4f_idx_and_more'),
        ('rooms', '0007_room_base_price'),
        ('staff', '0005_staffprofile_staff_profi_tenant__15eb36_idx'),
        ('tenants', '0005_tenant_max_properties_tenant_max_rooms_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['tenant', 'property', 'check_in_date', 'check_out_date'], name='bookings_tenant__5ef0d5_idx'),
        ),
    ]
