# Generated by Django 6.1 on 2026-08-25 16:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_expense_date'),
        ('properties', '0002_alter_property_status'),
        ('tenants', '0005_tenant_max_properties_tenant_max_rooms_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'account_heads',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-expense_date', '-id']},
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='expenses_categor_80dcb8_idx',
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash / Counter Drawer'), ('BANK_TRANSFER', 'Bank Transfer'), ('CARD', 'Credit / Debit Card'), ('ONLINE', 'Online / Wallet')], default='CASH', max_length=30),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt_image',
            field=models.FileField(blank=True, null=True, upload_to='expense_receipts/'),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt_number',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.expensecategory'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='expense',
            name='item_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='expense',
            name='vendor_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='accounthead',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_heads', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='expense',
            name='account_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.accounthead'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['account_head'], name='expenses_account_bd852e_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['payment_method'], name='expenses_payment_b96059_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='accounthead',
            unique_together={('tenant', 'name')},
        ),
    ]
