# Generated by Django 6.1 on 2026-09-18 10:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_accounthead_alter_expense_options_and_more'),
        ('properties', '0003_remove_property_properties_city_c34f4f_idx_and_more'),
        ('tenants', '0005_tenant_max_properties_tenant_max_rooms_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['tenant', 'expense_date'], name='expenses_tenant__97ee9a_idx'),
        ),
    ]
