# Generated by Django 6.1 on 2026-09-24 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_expense_expenses_tenant__97ee9a_idx'),
        ('properties', '0003_remove_property_properties_city_c34f4f_idx_and_more'),
        ('tenants', '0005_tenant_max_properties_tenant_max_rooms_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accounthead',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='accounthead',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_heads', to='properties.property'),
        ),
        migrations.AlterUniqueTogether(
            name='accounthead',
            unique_together={('tenant', 'property', 'name')},
        ),
    ]
