# Generated by Django 6.1 on 2026-09-25 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_alter_accounthead_unique_together_and_more'),
        ('tenants', '0005_tenant_max_properties_tenant_max_rooms_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accounthead',
            unique_together={('tenant', 'name')},
        ),
        migrations.RemoveField(
            model_name='accounthead',
            name='property',
        ),
    ]
