# Generated by Django 6.1 on 2026-08-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Maintenance'), ('CLEANING', 'Cleaning')], db_index=True, default='AVAILABLE', max_length=50),
        ),
    ]
