# Generated by Django 6.1 on 2026-08-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='housekeeping_status',
            field=models.CharField(choices=[('CLEAN', 'Clean'), ('DIRTY', 'Dirty'), ('IN_PROGRESS', 'In Progress'), ('INSPECTED', 'Inspected')], db_index=True, default='CLEAN', max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('RESERVED', 'Reserved'), ('CLEANING', 'Cleaning'), ('MAINTENANCE', 'Maintenance')], db_index=True, default='AVAILABLE', max_length=50),
        ),
    ]
