# Generated by Django 6.1 on 2026-08-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_housekeeping_status_alter_room_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate per hour for short stay', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='is_hourly_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate per hour for short stay', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='is_hourly_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
