# Generated by Django 6.1 on 2026-08-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_room_hourly_rate_room_is_hourly_allowed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.JSONField(blank=True, default=list, help_text='Room specific amenities override'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='amenities',
            field=models.JSONField(blank=True, default=list, help_text='Room type default amenities list'),
        ),
    ]
