# Generated by Django 6.1 on 2026-08-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_remove_property_properties_city_c34f4f_idx_and_more'),
        ('rooms', '0005_room_amenities_roomtype_amenities'),
        ('tenants', '0005_tenant_max_properties_tenant_max_rooms_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomtype',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='room',
            name='rooms_room_nu_5c8eca_idx',
        ),
        migrations.RenameIndex(
            model_name='room',
            new_name='idx_room_tenant_prop_stat',
            old_name='rooms_tenant__e96fb8_idx',
        ),
        migrations.RenameIndex(
            model_name='roomtype',
            new_name='idx_rtype_tenant_prop',
            old_name='room_types_tenant__a5e7c6_idx',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['tenant', 'room_type'], name='idx_room_tenant_type'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['tenant', 'room_number'], name='idx_room_tenant_num'),
        ),
        migrations.AddIndex(
            model_name='roomtype',
            index=models.Index(fields=['tenant', 'is_active'], name='idx_rtype_tenant_active'),
        ),
    ]
