# Generated by Django 6.1 on 2026-08-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_roomtype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Room specific base price override per night', max_digits=10, null=True),
        ),
    ]
